# Generated by Django 3.0.8 on 2021-06-23 05:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('Question1', models.CharField(max_length=128)),
                ('Question2', models.CharField(max_length=128)),
                ('Question3', models.CharField(max_length=128)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
