# Generated by Django 3.0.8 on 2021-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bg',
            field=models.CharField(default='netherrack', max_length=32),
        ),
    ]
