# Generated by Django 3.0.8 on 2021-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Age',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='member',
            name='Description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='Hobbies',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='Question1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='Question2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='Question3',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
