# Generated by Django 3.0.8 on 2021-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp', '0002_auto_20210623_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
